version: '3.8'
services:
  webapp:
    build: 
      context: ./
      dockerfile: docker/Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./src:/usr/src/app
    environment:
      - PYTHONUNBUFFERED=1
      - STREAMLIT_RUN_ON_SAVE=true

